### PR TITLE
Changed structure to use width in details and images

### PR DESCRIPTION
**Pull request by kalicki**
Hi @probil!

**Problem**: It is not possible to manipulate the width of the class `block-image` and`block-details` on the outside without having to change the component.

**Idea**: To improve the usefulness I added options to manipulate the size of each block. 

**Check new options**:

| Name | Type | Default | Required | Description |
| --- | --- | --- | --- | --- |
| `width-block-image` | String | `70%` | `false` | Handles the `min/max-width` of the class`block-image` |
| `width-block-details` | String | `30%` | `false` | Handles the `min/max-width` of the class `block-details` |

### CODE REVIEW

**Comment by probil** [comment]
Wow! Good idea. I will merge your PR after little review. Thanks

Other ideas I have:
- add ability to move previews from the `left` to the `top` or `bottom` (prop)
- make slider work after screen resize to the mobile screen and back to the wide screen. (currently not working)
- separate css from the component, so users can apply own styles (like themes) without overwriting those

**Comment by kalicki** [comment]
News?

**Comment by probil** [comment]
Hmmm. I think it should be renamed this way:
`width-block-image` -> `image-block-width`
`width-block-details` -> `details-block-width`

And also, we can make only one prop, for example `details-block-width`. And another one can be computed. I mean, if `details-block-width=75%` so `image-block-width` can be computed as 25% (100-75=25). 
Make some sense for you?

Also, why we should replace `right` with `max-width`? I don't disagree but I want to know why. :)

**Comment by kalicki** [comment]
> Hmmm. I think it should be renamed this way:
> width-block-image -> image-block-width
> width-block-details -> details-block-width

I don't know either way, that's not relevant, but rather like this:
`width-block-*` or `block-width-*`

> And also, we can make only one prop, for example details-block-width. And another one can be computed. I mean, if details-block-width=75% so image-block-width can be computed as 25% (100-75=25). 
> Make some sense for you?

That's cool, but who knows in the future. I think?!

> Also, why we should replace right with max-width? I don't disagree but I want to know why. :)

Ok, now there's handling of `width` then use `right` wouldn't be the best idea (I think), so I used `min | max-width` since only `width` impairs the effects...

**Pull request closed without merging**
